# Assignment Applied Machine Learning BSc IK 

## Notebook made by

**Gebruik graag dit formaat**

* Voor de namen:  voornaam rest van je naam, voornaam rest van je naam,....
* je studentnummers: hetzelfde: scheidt met `,`
* je emails: hetzelfde: scheidt met `,`
* voor je groep: **alleen de hoofdletter** (iets als  `A` of `B` dus)

__Namen__: Edwin Brüss

__Emails__: edwin.bruss@student.uva.nl

__Student ids__ : 13967223

__Groep__ : B

## Toelichting

* Een aantal opgaven worden automatisch nagekeken. Bij vrijwel alle opdrachten staan er een paar tests onder de opdracht, dit is voornamelijk om te zorgen dat je de juiste type output geeft. Dit zijn dus *NIET* alle tests, die komen er bij het graden nog bij.
* Elke vraag is 1 punt waard, tenzij anders aangegeven. Soms is die punt onderverdeeld in deelpunten, maar niet altijd. 

## Voor het inleveren!

* Pas niet de cellen aan, vooral niet die je niet kunt editen. Dit levert problemen op bij nakijken. Twijfel je of je per ongeluk iets hebt gewijzigd, kopieer dan bij inleveren je antwoorden naar een nieuw bestand, zodat het niet fout kan gaan.

* Zorg dat de code goed runt van boven naar beneden, verifieer dat door boven in Kernel -> Restart & Run All uit te voeren

## Na het inleveren!

* Het gebeurt erg vaak dat mensen een "leeg bestand" inleveren. Vaak een andere versie van de opgave die nog ergens op je computer rondslingerde. Zonde van al je werk toch!
* Dus, lever **minstens een half uur voor tijd in**. Download dan wat je hebt ingeleverd op Canvas. Geef het een andere naam om verwarring te voorkomen. En draai alle cellen, en bekijk het. Geen syntax fouten? Alle vragen gemaakt? Dan zit het vast wel goed, en hoef je niet in de zenuwen te zitten.

# Applied Machine Learning W1
 

In [1]:
!pip install nose

Defaulting to user installation because normal site-packages is not writeable


In [2]:
import os
import sys

import numpy as np
import pandas as pd
import seaborn as sns

import sklearn
from scipy.stats import mode
from nose.tools import assert_count_equal, assert_equal
from numpy.testing import *
from pandas.testing import assert_frame_equal
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn import datasets
# Please do not remove this: 
np.random.seed(31415)

# Theory

With these questions you and your group will practice your ability to formulate key concepts precisely and short. 
Such questions  also appear in the exams, and are graded quite strict.

Always answer in one grammatically correct English sentence. 

Finish the following sentences:

1. Machine learning algorithms build a model ...
2. Machine learning can be divided into three parts, namely .....
3. Each of these 3 parts can be described as follows:
    1. .... is ....
    1. .... is ....
    1. .... is ....
4. The key difference between regression and classification problems is .....


1. Machine learning algorithms build a model of data.
2. Machine learning can be divided into three parts, namely unsupervised learning, supervised learning and reinforcement learning.
3. A. Unsupervised learning is grouping and sorting. B. Supervised learning is classifying and predicting. Reinforcement learning is dealing in new situations and learning from feedback from it.
4. The key difference between regression and classification problems is that classification is categoric and regression is numeric.

# Part 0 classification with the iris data set, using knn

In [3]:
#https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_iris.html
iris= datasets.load_iris()

X,y= iris.data, iris.target
print(X.shape,y.shape)
print(X[:5])
print(y)

(150, 4) (150,)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


# train test

Use `np.random.choice` to create random `X_train, X_test, y_train, y_test`  such that 

1. 90 train, 60 test
2. Stratified, so an equal amount of cases from each of the three classes in the train and test sets.

Make tests to test that what you create is according to these specs.

## Note about our questions, and how to answer them

Here and later we may ask you to program things explicitly, and thus **not** using a scikit learn or other routine. Please do so, and practice this. We will do the same in the exam. It is important that you understand the algorithms behind the concepts that you use. That is the reason. Also we believe that you understand and remember things better when you have programmed than from scratch.

Of course you can google the answer in a few minutes and copy-paste it. But does that give your satisfaction or gratification? Do you *learn* anything from it? Please do not work like that. You make these assignments with 4 students, so you really have a lot of time. Make them all, compare and discuss the 4 found solutions, improve and refactor  them to one super great siolution. And, if all this does not appeal to you, then maybe this does: at the exam we will also ask these questions, and you do not have access to the web then. 

### making tests

This is an underdeveloped skill with many students. Why? Testing your own answer gives you a good feeling, it often lets you improve your answer, and can also be seen as a way to find the (complete) answer. **Please practice it and take it seriously.** At the exam you will have a notebook too, and so you can also test your own answers. Being skillfull in testing will boost your grade.

In [4]:
X_train, y_train, X_test,  y_test =[],[],[],[] # replace by your answer
#WRITE YOUR CODE HERE

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, stratify = y)

for M in [X_train, y_train, X_test,  y_test]:
    print( M.shape)
print(y_test)

(90, 4)
(90,)
(60, 4)
(60,)
[1 0 2 2 2 0 0 1 2 2 0 2 0 2 2 0 0 1 1 1 0 2 1 0 1 0 1 2 1 0 1 0 1 0 0 2 2
 1 2 2 0 0 1 1 0 2 1 0 1 2 0 1 2 2 2 0 2 1 1 1]


In [5]:
assert_equal(X_train.shape,(90, 4))
assert_equal(X_test.shape,(60, 4))
assert_equal(y_train.shape,(90, ))
assert_equal(y_test.shape,(60, ))

# knn classifier

Program from scratch a knn classifier which can work on data `X` and `y` as you have from the iris dataset.

It returns the most common label in the k nearest neighbors.

### Hints

* use `euclidean` as your distance function
* `X_train[0,:]` picks out the first instance from `X_train`.
* Use *fancy indexing* to take out a number of items from a numpy array. as in `X[8,35,7,2]`.
* `np.argsort` is handy.

In [6]:
from scipy.stats import mode
from scipy.spatial.distance import euclidean

def knn(X,y,example,k=5):
    '''Classify example using majority vote of the k closest items in X with labels y.'''
    #WRITE YOUR CODE HERE

    Distances = [euclidean(example,X[i]) for i in range(X.shape[0])]
    
    kNN_Y = y[np.argsort(Distances)[:k]]
    
    return mode(kNN_Y)[0][0]


[ knn(X_train,y_train,i) for i in X_test[:1]] 

C:\Users\edwin\AppData\Local\Temp\ipykernel_4436\2865543777.py:12: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  return mode(kNN_Y)[0][0]


[1]

# Evaluate

Run knn on `X_test` and compare the outcomes to `y_test`.

Come up with a useful and insightfull error report.

In [7]:
#WRITE YOUR CODE HERE


y_pred = [knn(X_train,y_train,i) for i in X_test]
print('accuracy', (np.array(y_test)==np.array(y_pred)).mean())

for i in (0,1,2):
    Xi,yi=X_test[y_test==i], y_test[y_test==i]
    yi_pred=[knn(X_train,y_train,j) for j in Xi]
    errors=[j for j in yi_pred if j!=i]
    print('accuracy for label',str(i),'is', (np.array(yi)==np.array(yi_pred)).mean(),'errors are', errors)



accuracy 1.0
accuracy for label 0 is 1.0 errors are []
accuracy for label 1 is 1.0 errors are []
accuracy for label 2 is 1.0 errors are []


C:\Users\edwin\AppData\Local\Temp\ipykernel_4436\2865543777.py:12: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  return mode(kNN_Y)[0][0]


# Make more efficient

1. Estimate what work is done when running knn on one new to be classified instance, given that it has $n$ training examples. 
2. How expensive is the sorting step?
3. Remove the sorting step by programming a heap of size $k$ which contains from the train set already inspected  the $k$ closest instances to the unseen example.

1. n times n
2. depends on the sorting algorithm, but normally n times n
3. 

In [8]:
def knn_heap(X,y,example,k=5):
    '''Classify example using majority vote of the k closest items in X with labels y.'''
    #WRITE YOUR CODE HERE
    
    Distances = [euclidean(example, X[i]) for i in range(X.shape[0])]
    L = [i for i in range(X.shape[0])]
    D = np.array((L, Distances))
    
    heap = np.array(([i for i in range(k)], Distances[:k]))
    
    for i in range(D.shape[1]):
        if D[1][i] < heap[1][k-1] and D[0][i] not in heap[0]:
            heap[1][k-1] = D[1][i]
            heap[0][k-1] = D[0][i]
            
            heap[0] = heap[0][np.argsort(heap)[1]]
            heap[1] = heap[1][np.argsort(heap)[1]]    
    H = []
    
    for i in range(heap.shape[1]):
        H.append(int(heap[0][i]))
        
    kNN_Y = y[H]
    
    return mode(kNN_Y)[0][0]


[ knn_heap(X_train,y_train,i) for i in X_test[:5]] 

 

C:\Users\edwin\AppData\Local\Temp\ipykernel_4436\3639592180.py:25: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  return mode(kNN_Y)[0][0]


[1, 0, 2, 2, 2]

# Predicting a value with knn-regression

## Part 1: Loading the data into a Pandas Data Frame  

The descriptions of the columns of the dataset can be found here:

**pop**: population

**pctUrban**: percentage of people living in areas classified as urban

**medIncome**: Median Income

**pct12-29**: percentage of population that is 12-21 in age

**pct65up**: percentage of population that is 65 and over in age

**pctPoverty**: percentage of people under the poverty level

**pctAllDivorc**: percentage of population who are divorced

**pctUnemploy**: percentage of people 16 and over, in the labor force, and unemployed

**perHoush**: mean persons per household

**pctHousOccup**: percent of housing occupied

**persHomeless**: number of homeless people

**persEmergShelt**: number of people in homeless shelters

**nonViolPerPop**: total number of non-violent crimes per 100K popuation

**State**: the state in which this town/city is located

**countyCode**: the code number of the county of the state this town/city is located



### Question 1a:
Load the data into a Pandas DataFrame. At this point, make sure that you only load the following columns: 

`'pop', 'pctUrban', 'medIncome', 'pct12-29', 'pct65up', 'pctPoverty', 'pctAllDivorc', 'pctUnemploy', 'perHoush', 'pctHousOccup', 'persHomeless', 'persEmergShelt', 'nonViolPerPop'`


Here and elsewhere, when we load data, always use the `loadfile()` command. Like in `pd.read_csv(loadfile())`. We do this because when we (auto)grade we have the file not in the same directory as the notebook.

In [9]:
def loadfile():
    if 'crime_data.csv.gz' in os.listdir():
        return 'crime_data.csv.gz'
    elif os.path.exists('../../data/Week1/'):
        return '../../data/Week1/crime_data.csv.gz'
    elif os.path.exists('../../../data/Week1/'):
        return '../../../data/Week1/crime_data.csv.gz'
    


In [10]:
# Load the dataset
crime_data = loadfile()

crime_data = pd.read_csv(crime_data, usecols= ['pop', 'pctUrban', 'medIncome', 'pct12-29', 'pct65up', 'pctPoverty', 'pctAllDivorc', 'pctUnemploy', 'perHoush', 'pctHousOccup', 'persHomeless', 'persEmergShelt', 'nonViolPerPop'])

#WRITE YOUR CODE HERE

print(crime_data.shape)
crime_data.head()

(949, 13)


perHoush  pct12-29  pct65up  pctUrban  pctPoverty  pctUnemploy  \
0      3.10     21.44    11.33     100.0        1.96         2.70   
1      2.82     21.30    17.18     100.0        3.98         2.43   
2      2.76     40.53    12.65       0.0       29.99         9.08   
3      2.60     27.41    14.42     100.0        4.01         4.85   
4      2.46     35.16     8.58     100.0       13.68         4.18   

   pctAllDivorc  pctHousOccup  persEmergShelt  persHomeless  nonViolPerPop  \
0          4.47         98.37              11             0        1394.59   
1          5.42         97.15               0             0        1955.95   
2          9.73         92.45               2             0        9988.79   
3          7.64         95.11               0             0        1890.88   
4          8.64         95.07             125            15        4747.58   

   medIncome      pop  
0    75122.0  11980.0  
1        NaN  23123.0  
2        NaN      NaN  
3    42805.0  28700.0  
4        NaN  74111.0

In [11]:
assert_equal(crime_data.shape,(949, 13))
assert_count_equal(crime_data.columns,['pop',
            'pctUrban',
            'medIncome',
            'pct12-29',
            'pct65up',
            'pctPoverty',
            'pctAllDivorc',
            'pctUnemploy',
            'perHoush',
            'pctHousOccup',
            'persHomeless',
            'persEmergShelt',
            'nonViolPerPop'
           ])

### Question 1b:
We want to predict the number of crimes. Identify the features X and the target variable Y, and turn the X and Y DataFrames into Numpy arrays.

Make sure `Y` is of shape `(949, 1)`.

In [12]:
X = crime_data[['pop', 'pctUrban', 'medIncome', 'pct12-29', 'pct65up', 'pctPoverty', 'pctAllDivorc', 'pctUnemploy', 'perHoush', 'pctHousOccup', 'persHomeless', 'persEmergShelt']]
Y = crime_data[['nonViolPerPop']]

X = X.to_numpy()
Y = Y.to_numpy()

display(Y.shape)
#WRITE YOUR CODE HERE
print(X.shape,Y.shape)
print(X[:3])
print(Y[:5])

(949, 1)

(949, 12) (949, 1)
[[1.1980e+04 1.0000e+02 7.5122e+04 2.1440e+01 1.1330e+01 1.9600e+00
  4.4700e+00 2.7000e+00 3.1000e+00 9.8370e+01 0.0000e+00 1.1000e+01]
 [2.3123e+04 1.0000e+02        nan 2.1300e+01 1.7180e+01 3.9800e+00
  5.4200e+00 2.4300e+00 2.8200e+00 9.7150e+01 0.0000e+00 0.0000e+00]
 [       nan 0.0000e+00        nan 4.0530e+01 1.2650e+01 2.9990e+01
  9.7300e+00 9.0800e+00 2.7600e+00 9.2450e+01 0.0000e+00 2.0000e+00]]
[[1394.59]
 [1955.95]
 [9988.79]
 [1890.88]
 [4747.58]]


In [13]:
assert isinstance(X, np.ndarray)
assert isinstance(y, np.ndarray)
assert_equal(X.shape,(949, 12))
assert_equal(Y.shape,(949, 1))

## Part 2: Split the data into a training set and a test set 
### Question 2:
Split the data into a training and a test set, using teh appropriate sklearn function. Use a  70%-30% split.  
Print the number of examples in the training set and the test set.

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.30)

#WRITE YOUR CODE HERE
for M in [X_train, X_test, Y_train, Y_test]:
    print(M.shape)

(664, 12)
(285, 12)
(664, 1)
(285, 1)


In [15]:
assert X_train.shape== (664, 12)
assert Y_test.shape== (285,1)


## Part 3: Knn Regression [2 pts]

In [16]:
# figure out what this means, and what does it mean when taking the sum?
crime_data.isna().sum()
# Hoeveel nas er zijn.

perHoush           0
pct12-29           0
pct65up            0
pctUrban           0
pctPoverty         0
pctUnemploy        0
pctAllDivorc       0
pctHousOccup       0
persEmergShelt     0
persHomeless       0
nonViolPerPop      0
medIncome         95
pop               95
dtype: int64

In [17]:
np.isnan(X_test).sum(0)

array([32,  0, 28,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [18]:
np.isnan(X_test[:,0]).sum()

32

**Missing Data**: Often the data you are considering is incomplete. For example in some city, the number of homeless people might be unknown. In this case, if you look into the datasets you will find the value *NaN*. This is not a real value, hence Linear Regression cannot handle it.

The question is how can we handle missing data. There are many ways to do so, some more sophisticated than others. Here we will use a simple approach. This simple approach fills in the missing values, i.e. replaces the *NaN* by the median of the corresponding feature. E.g. if there is a *NaN* value for the population in one city, this *NaN* value will be replaced by the median number of the population in all other cities in the data.

1. figure out what this code  `np.isnan(X_test).sum(axis=0), np.isnan(X_train).sum(axis=0) `    is doing. Remove the `axis=0`, and replace it by `axis=1`. You get it?
2. What is the median of the values in the first column of `X_test`?  (variable `v2`)
    * Why does `np.median` not work ;-) You are close though! 
3. Create the first column of X_test in which you replaced all nan values by the median of the first column. (variable `v3`)
5. Then do this for all columns at once   using Scikit learn's `SimpleImputer`.
    * So the new `X_train` and `X_test` have no more missing values.
6. Check that you get exactly the same result using your own method and sklearn's.  

In [19]:

#1. Aantal nans per kolom, axis = 1 is aantal nans per rij. Returnt een array.
#2. Werkt niet omdat er nans inzitten, die moeten er eerst uit. En median moet per kolom, niet voor alles.
#3. Kijk per element in de array of het nan is, zoja: vervang met mediaan.

v2 = np.nanmedian(X_test[:,0])

v3 = X_test[:,0]

for i in range(len(v3)):
    if np.isnan(X_test[:,0][i]):
        v3[i] = v2

print(v2)
print(v3[:10])
print(np.isnan(v3).sum())
# naize test
# all places in v3 which were nan in  X_test[:,0] are now equal to v2
print(v3[np.isnan(X_test[:,0])]==v2)

20999.0
[21282. 17651. 20999. 28335. 20999. 20999. 15512. 10978. 34874. 10830.]
0
[]


In [20]:
assert isinstance(v2,np.float) 
assert np.isnan(v3).sum()==0

C:\Users\edwin\AppData\Local\Temp\ipykernel_4436\346195263.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  assert isinstance(v2,np.float)


In [21]:
# Fill in the missing data in the dataset (i.e. replace NaN values in both X_train and X_test) 
from sklearn.impute import SimpleImputer

imp_median = SimpleImputer(missing_values=np.nan, strategy='median')
imp_median.fit(X_train)
imp_median.fit(X_test)
X_train = imp_median.transform(X_train)
X_test = imp_median.transform(X_test)

#WRITE YOUR CODE HERE
print(np.isnan(X_train).sum())
print(np.isnan(X_test).sum())
print(X_test[:,0])

0
0
[ 21282.  17651.  20999.  28335.  20999.  20999.  15512.  10978.  34874.
  10830.  50024.  20393.  14507.  72884.  30087.  33233.  49832. 189126.
  44630.  51003.  20999.  20999.  15066.  13882.  15616.  50452.  14771.
  20999.  28158.  12183.  10940.  20999.  10241.  51618.  15850.  12805.
  20999.  17118.  28199.  56475.  20079.  35418.  13852.  14637.  85427.
  11980.  33687.  11294.  51288.  30510.  30250. 606900.  14558.  10888.
  69348.  52141.  56958.  11843.  18820.  20608.  11590.  20999.  19899.
  10415.  40283.  22676.  20999.  28808.  18659.  11523.  35309.  29541.
  13243.  13057.  10971.  12697.  10130.  47089.  50889.  13055.  20999.
  16569. 111183.  17192.  20999.  24825.  12649.  11314.  20999.  12358.
  10325.  23285.  10687.  27099.  23644.  20999.  34997.  21564.  25430.
  20999.  48718.  15004.  18734.  39983.  34598. 286215.  20999.  25058.
  13692.  28844.  38686.  23330.  19163.  17625.  13176. 130474.  13894.
  92703.  20999.  20999.  28334.  13989.  19572

In [22]:
assert_equal(np.isnan(X_train).sum(),0)
assert_equal(np.isnan(X_test).sum(),0)


# Check that you get exactly the same result using your own method and sklearn's.



In [23]:
print(v3 == X_test[:,0])
print(np.all(v3 == X_test[:,0]))

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  T

# KNN

Make now the KNN regression algorithm from scratch.

* use euclidean again 
* use `np.argsort` and `[:k]` to find the indexes of the k nearest neighbor rows
* use so called *fancy indexing* on numpy array 
    * `X_train[[2,5,3]]` gives the 2D array with the 2nd, 5th and 3rd row of `X_train`.


## Evaluate with RMSE (root mean square error)

1. Program the formula for RMSE from scratch 
2. Compute `Y_predicted`
3. Compute the RMSE for the kNN algorithm on this dataset.

## Do the same for $R^2$.

In [24]:
from scipy.spatial.distance import euclidean


def  knn(ExamplesX,ExamplesY,instance,k=5):
    
    #Lijst met alle distances (euclidean)
    L = [euclidean(instance, ExamplesX[i]) for i in range(ExamplesX.shape[0])]

    kNN_Y = ExamplesY[np.argsort(L)[:k]]
   
    return kNN_Y.mean()


knn(X_train,Y_train,X_test[0,:]), Y_test[0]

(2071.4980000000005, array([1560.37]))

In [25]:
def rmse(u,v): ## u, v are 1D arrays of the same length
    
    SquaredErrors = [(u[i] - v[i])**2 for i in range(len(u))]
    mse = np.mean(SquaredErrors)
    root = np.sqrt(mse)
    return root

rmse([2,3,5,6,7,34],[2,3,5,6,7,34])

0.0

In [26]:
def rsquare(predicted,true): ## u, v are 1D arrays of the same length
    mean = np.mean(true)
    sst = sum([(i-mean)**2 for i in predicted])
    ssr = sum([(predicted[i] - true[i])**2 for i in range(len(predicted))])
    rsquare = ssr/sst
    return rsquare

rsquare([2,3,5,6,7,34],[2,3,5,6,7,34])

0.0

In [27]:
print(X_test.shape)
Y_predicted = np.array([[knn(X_train, Y_train, i)] for i in X_test])
RMSE = rmse(Y_predicted,Y_test)


Y_predicted.shape,RMSE 

(285, 12)


((285, 1), 1913.778533594779)

# What is happening here?

* Explain what we are doing in the next cell.
* Is this according to your intuition?

In [28]:
from sklearn.neighbors import KNeighborsRegressor

neigh = KNeighborsRegressor(n_neighbors=5)
neigh.fit(X_train, Y_train)

Y_predicted2= neigh.predict(X_test )

rmse(Y_predicted2,Y_test)

1913.778533594779

Predict y based on X_test with the built in function of sklearn. Not to my intuition because the code is neigh.predict(X_test), but it is actually the y value that we are predicting

# Normalization


## Z- transformation

* We transform the data such that each kolom has a mean of 0 and a standard deviation of 1.

## Unit normalization

* We transform the data such that each row has unit norm.
* A unit normn of a vector $v$ means that its length equals 1, that is $\sqrt{v\cdot v}$ equals 1, where $v\cdot v$ is the dot product of $v$ with itself, that is $\Sigma_i v_i\cdot v_i$.


## Your task

* Implement both normalisations of a matrix and **make tests to check that they work correctly**.
    * Check out `np.linalg.norm?`
    * Tests are real computer tests. Not a print that you then check with your eyes.
    * So use `assert` statements, or make a test which returns True.
    * Of course you may add a useful print. 
* Do not use predefined functions for these normalisations, but program them from the here given definitions.
* Finally check that they give the same results as the [scikit learn normalizer](https://scikit-learn.org/stable/modules/preprocessing.html#normalization) and [standardizer](https://scikit-learn.org/stable/modules/preprocessing.html#standardization-or-mean-removal-and-variance-scaling).

In [29]:
# Assume M is a np.array
def standardize(M):
    for j in range(len(M[0,:])):
        mean = np.mean(M[:,j])
        std = np.std(M[:,j])
        for i in range(len(M[:,j])):
            M[:,j][i] = (M[:,j][i] - mean) / std
    return(M)
    
def normalize(X):
    for i in range(len(X[:,0])):
        norm = np.linalg.norm(X[i,:])
        for j in range(len(X[i,:])):
            X[i,:][j] = abs(X[i,:][j]) / norm
    return(X)
    
X = np.array([[ 1., -1.,  2.],
              [ 2.,  0.,  0.],
              [ 0.,  1., -1.]])  

print(standardize(X))
print(normalize(X))

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]
[[0.         0.67566392 0.73720978]
 [0.97700842 0.         0.21320072]
 [0.60172167 0.60172167 0.52522573]]


Here in the answer cell below:

* your own tests
*  tests that scikit learn functions do the same


In [30]:
from sklearn import preprocessing
scaler = preprocessing.StandardScaler().fit(X)

X_scaled = scaler.transform(X)
X_normalized = preprocessing.normalize(X)

print(X_normalized == normalize(X))
print(X_scaled == standardize(X))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[False  True  True]
 [False  True  True]
 [False  True False]]


In [31]:
assert_equal(X.shape, normalize(X).shape)
assert_equal(X.shape, standardize(X).shape)


### Question 3
 
 
* Do the KNN regression again but now on the normalized data.
* Conclude.

In [32]:
Y_predicted = np.array([[knn(normalize(X_train), normalize(Y_train), i)] for i in X_test])
RMSE = rmse(Y_predicted,Y_test)
RMSE
# De data was al genormaliseerd?

4318.647485206126

# Improving KNN

With KNN each neighbour is equal, as we take the mean or the majority class. Now, we may change KNN by *weighing* the imprtance of the neighbors, for instance with the distance or similarity. 

Implement that improvement:

* find an easy way to create weights from distances.
* normalize these weighjts so that the weights of all neighbours add up to 1.
* find out the wonderfullness of the *dot product*, see how you take the dot product of 2 numpy arrays, and, well, use it to compute the weighted mean, basically by saying *weights times values*. 

* Work it out using the tips dataset for which you predict the tip from the total bill.
* Do all steps we do in an ML project and predict the tip using KNN regression with weighted neighbors.

 

In [33]:
tips = sns.load_dataset('tips')
print(tips.shape)
sns.regplot(x='total_bill', y='tip', data=tips);
tips.head()

(244, 7)


total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

# Male vs Female

We  wonder if males tip differently than females. We first investigate visually. Then we compute.

1. Add `hue='sex'` to the `sns.scatterplot` command. 
2. Simply plot two regplots on top of each other, one for the males, one for the females.
   * Of course you use Boolean indexing to restrict `data` to the required sex.
3. Read up what those shaded areas in the `regplot` mean. Can you draw a conclusion about male vs female tipping?
4. Finally run your weighted KNN and a scikit learn linear regression, and plot the regression line, the true values and the KNN-predicted tips for the test-set. Can you conclude something?

In [57]:
sns.regplot(x='total_bill', y='tip', data=tips.loc[(tips.sex == 'Female')]);
sns.regplot(x='total_bill', y='tip', data=tips.loc[(tips.sex == 'Male')]);
#confidence interval, niet heel verschillend